name: local_push_connectivity
description: "a local network Apple Local Push Connectivity"
version: 0.0.5-beta.4
homepage: https://github.com/ho-doan/local_push_connectivity

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.hodoan.local_push_connectivity
        pluginClass: LocalPushConnectivityPlugin
      ios:
        pluginClass: LocalPushConnectivityPlugin
      linux:
        pluginClass: LocalPushConnectivityPlugin
      macos:
        pluginClass: LocalPushConnectivityPlugin
      windows:
        pluginClass: LocalPushConnectivityPluginCApi
      web:
        pluginClass: LocalPushConnectivityWeb
        fileName: local_push_connectivity_web.dart